language: node_js
node_js:
  - '12.1'
script:
  - npm run lint
  - npm test
notifications:
  slack:
    secure: mvBLbHwbJTtfEQ7UPRA1/PupeX7v6VPuwTyZbCL1bo+b5owrkP98pbwE4lTvWPkJcGLAgS0j8mkQ/2DpjoeupTizgNOC7b5dcjRFiMoPq6P03KIN0kM8XAQVdfhMolnB4JLTxyIpNvFWDpmg6kwIVn/Kz5ui+N2WgRfWaMnEJYoYrL5dcOQ3aaX4mZ2PK1JKiltnMNk1sv6u/OOvq76F0IRE6SIBS5LQWtXqlt2UcjAQto/jpnfuAoY/QgNmSoux+jCAOdmko5TZzhYu2w8hgnNCCPas1zk7j9FuZoCUFoeFwL20WVWlFZua+W6jJN+l9XayNoD1egGKZHrXh/HKVARNCycPnGH6H3WP7OyRO3gDgy4EPpG7YbF+8IK6jlyoFwdBrTXIclB7FTSh/QU0aLmrUrPbhqE9FDGS4QeqXp2DE8e2tm6vtsg9WF8Zl8X3jN85ZxLA/GGBUWTQKevg3KhThvsBir2jK7Wj/j93YlA5Ea8VykbsP+JRTeBd1Tts4HpuJ9y9lGSGKfXYzDgOOZYYWtFy0BfcPwq+L4a+x43jQ8NMBKZXVrL+kORe2+POddtwfjrLN5DUsKSfC2Axzdcf6OyzIJ//UsbYKDrMbGXiSQ+kfTCJAZRotbX3ZoeczdLN13rN+Sr1Y7qiwyTpVnqUHmrz91NSaLzTRJqpzkw=
